config/routes.rb
Rails.application.routes.draw do
  resources :arts
  resources :biblicals
  resources :learns
  resources :authors
  resources :saints
  devise_for :users
  resources :users
  resources :events
  resources :slides
  get 'slideshows' => 'slideshows#index'
  get 'settings' => 'settings#index'
  post 'settings' => 'settings#create'
  patch 'settings' => 'settings#update'
  resources :students
  root to: 'home#index'
end

app/models/art.rb
class Art < ApplicationRecord
  has_attached_file :picture, styles: { full: "1920x1080>", large: "1066x600>", medium: "533x300>", thumb: "177x100#" }
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/author.rb
class Author < ApplicationRecord
  has_attached_file :picture, styles: { medium: "533x300>", thumb: "177x100#" }
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/biblical.rb
class Biblical < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/learn.rb
class Learn < ApplicationRecord
end

app/models/saint.rb
class Saint < ApplicationRecord
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/slide.rb
class Slide < ApplicationRecord
  has_attached_file :picture, styles: { full: "1920x1080>", large: "1066x600>", medium: "533x300>", thumb: "177x100#" }
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def login=(login)
  	@login = login
  end

  def login
  	@login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_hash).first
    end
  end

end

app/controllers/saints_controller.rb
class SaintsController < ApplicationController
  before_action :set_saint, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /saints
  # GET /saints.json
  def index
    @saints = Saint.all
  end

  # GET /saints/1
  # GET /saints/1.json
  def show
  end

  # GET /saints/new
  def new
    @saint = Saint.new
  end

  # GET /saints/1/edit
  def edit
  end

  # POST /saints
  # POST /saints.json
  def create
    @saint = Saint.new(saint_params)

    respond_to do |format|
      if @saint.save
        format.html { redirect_to @saint, notice: 'Saint was successfully created.' }
        format.json { render :show, status: :created, location: @saint }
      else
        format.html { render :new }
        format.json { render json: @saint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /saints/1
  # PATCH/PUT /saints/1.json
  def update
    respond_to do |format|
      if @saint.update(saint_params)
        format.html { redirect_to @saint, notice: 'Saint was successfully updated.' }
        format.json { render :show, status: :ok, location: @saint }
      else
        format.html { render :edit }
        format.json { render json: @saint.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saints/1
  # DELETE /saints/1.json
  def destroy
    @saint.destroy
    respond_to do |format|
      format.html { redirect_to saints_url, notice: 'Saint was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saint
      @saint = Saint.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def saint_params
      params.require(:saint).permit(:day, :name)
    end
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/biblicals_helper.rb
module BiblicalsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/learns_helper.rb
module LearnsHelper
end

app/helpers/saints_helper.rb
module SaintsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/helpers/slideshows_helper.rb
module SlideshowsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/saints/_form.html.erb
<%= form_with(model: saint, local: true) do |form| %>
  <% if saint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(saint.errors.count, "error") %> prohibited this saint from being saved:</h2>

      <ul>
      <% saint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :day %>
    <%= form.date_select :day, id: :saint_day, :default => { year: 2000 }, :discard_year => true %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :saint_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/saints/edit.html.erb
<h1>Editing Saint</h1>

<%= render 'form', saint: @saint %>

<%= link_to image_tag("/assets/ico/glasses.svg", height: '24', width: '24') + " Show", @saint, class: "btn btn-small btn-primary" %>
<%= link_to image_tag("/assets/ico/back.png", height: '24', width: '24') + " Back", saints_path, class: "btn btn-small btn-warning" %>

app/views/saints/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Saints</h1>

<table>
  <thead>
    <tr>
      <th>Day</th>
      <th>Name</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @saints.order(:day).each do |saint| %>
      <tr>
        <td><%= saint.day.strftime("%d %b") %></td>
        <td><%= saint.name %></td>
        <td><div class='btn-group'>
          <%= link_to image_tag("/assets/ico/glasses.svg", height: '24', width: '24') + " Show", saint, class: "btn btn-small btn-info" %>
          <%= link_to image_tag("/assets/ico/pencil.svg", height: '24', width: '24') + " Edit", edit_saint_path(saint), class: "btn btn-small btn-primary" %>
          <%= link_to image_tag("/assets/ico/trash.svg", height: '24', width: '24') + " Destroy", saint, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-small btn-danger" %>
        </div></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to image_tag("/assets/ico/add.svg", height: '24', width: '24') + " New Saint", new_saint_path, :method => :get, class: "btn btn-small btn-success" %>

app/views/saints/new.html.erb
<h1>New Saint</h1>

<%= render 'form', saint: @saint %>

<%= link_to image_tag("/assets/ico/back.png", height: '24', width: '24') + " Back", saints_path, class: "btn btn-small btn-warning" %>

app/views/saints/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Day:</strong>
  <%= @saint.day.strftime("%d %B") %>
</p>

<p>
  <strong>Name:</strong>
  <%= @saint.name %>
</p>

<%= link_to image_tag("/assets/ico/pencil.svg", height: '24', width: '24') + " Edit", edit_saint_path(@saint), class: "btn btn-small btn-primary" %>
<%= link_to image_tag("/assets/ico/back.png", height: '24', width: '24') + " Back", saints_path, class: "btn btn-small btn-warning" %>