config/routes.rb
Rails.application.routes.draw do
  resources :arts
  resources :biblicals
  resources :learns
  resources :authors
  resources :saints
  devise_for :users
  resources :users
  resources :events
  resources :slides
  get 'slideshows' => 'slideshows#index'
  get 'settings' => 'settings#index'
  post 'settings' => 'settings#create'
  patch 'settings' => 'settings#update'
  resources :students
  root to: 'home#index'
end

app/models/art.rb
class Art < ApplicationRecord
  has_attached_file :picture, styles: { full: "1920x1080>", large: "1066x600>", medium: "533x300>", thumb: "177x100#" }
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/author.rb
class Author < ApplicationRecord
  has_attached_file :picture, styles: { medium: "533x300>", thumb: "177x100#" }
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/biblical.rb
class Biblical < ApplicationRecord
end

app/models/event.rb
class Event < ApplicationRecord
end

app/models/learn.rb
class Learn < ApplicationRecord
end

app/models/saint.rb
class Saint < ApplicationRecord
end

app/models/setting.rb
class Setting < ActiveRecord::Base
end

app/models/slide.rb
class Slide < ApplicationRecord
  has_attached_file :picture, styles: { full: "1920x1080>", large: "1066x600>", medium: "533x300>", thumb: "177x100#" }
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def login=(login)
  	@login = login
  end

  def login
  	@login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_hash).first
    end
  end

end

app/controllers/biblicals_controller.rb
class BiblicalsController < ApplicationController
  before_action :set_biblical, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /biblicals
  # GET /biblicals.json
  def index
    @biblicals = Biblical.all
  end

  # GET /biblicals/1
  # GET /biblicals/1.json
  def show
  end

  # GET /biblicals/new
  def new
    @biblical = Biblical.new
  end

  # GET /biblicals/1/edit
  def edit
  end

  # POST /biblicals
  # POST /biblicals.json
  def create
    @biblical = Biblical.new(biblical_params)

    respond_to do |format|
      if @biblical.save
        format.html { redirect_to @biblical, notice: 'Biblical was successfully created.' }
        format.json { render :show, status: :created, location: @biblical }
      else
        format.html { render :new }
        format.json { render json: @biblical.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /biblicals/1
  # PATCH/PUT /biblicals/1.json
  def update
    respond_to do |format|
      if @biblical.update(biblical_params)
        format.html { redirect_to @biblical, notice: 'Biblical was successfully updated.' }
        format.json { render :show, status: :ok, location: @biblical }
      else
        format.html { render :edit }
        format.json { render json: @biblical.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /biblicals/1
  # DELETE /biblicals/1.json
  def destroy
    @biblical.destroy
    respond_to do |format|
      format.html { redirect_to biblicals_url, notice: 'Biblical was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_biblical
      @biblical = Biblical.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def biblical_params
      params.require(:biblical).permit(:quote, :source)
    end
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/biblicals_helper.rb
module BiblicalsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/learns_helper.rb
module LearnsHelper
end

app/helpers/saints_helper.rb
module SaintsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/helpers/slideshows_helper.rb
module SlideshowsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/biblicals/_form.html.erb
<%= form_with(model: biblical, local: true) do |form| %>
  <% if biblical.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(biblical.errors.count, "error") %> prohibited this biblical from being saved:</h2>

      <ul>
      <% biblical.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quote %>
    <%= form.text_area :quote, id: :biblical_quote %>
  </div>

  <div class="field">
    <%= form.label :source %>
    <%= form.text_field :source, id: :biblical_source %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/biblicals/edit.html.erb
<h1>Editing Biblical</h1>

<%= render 'form', biblical: @biblical %>

<%= link_to 'Show', @biblical %> |
<%= link_to 'Back', biblicals_path %>

app/views/biblicals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Biblicals</h1>

<table>
  <thead>
    <tr>
      <th>Quote</th>
      <th>Source</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @biblicals.each do |biblical| %>
      <tr>
        <td><%= biblical.quote %></td>
        <td><%= biblical.source %></td>
        <td><%= link_to 'Show', biblical %></td>
        <td><%= link_to 'Edit', edit_biblical_path(biblical) %></td>
        <td><%= link_to 'Destroy', biblical, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Biblical', new_biblical_path %>

app/views/biblicals/new.html.erb
<h1>New Biblical</h1>

<%= render 'form', biblical: @biblical %>

<%= link_to 'Back', biblicals_path %>

app/views/biblicals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote:</strong>
  <%= @biblical.quote %>
</p>

<p>
  <strong>Source:</strong>
  <%= @biblical.source %>
</p>

<%= link_to 'Edit', edit_biblical_path(@biblical) %> |
<%= link_to 'Back', biblicals_path %>